In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("china.csv")

C:\Users\Dell\AppData\Local\Temp\ipykernel_36680\3557151289.py:4: DtypeWarning: Columns (84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("china.csv")

In [44]:
df

,RecordNo,endtime,qweek,i1_health,i2_health,i7a_health,i3_health,i4_health,i5_health_1,i5_health_2,...,w5_96,w5_99,w5_98,w7,w9_1,w9_2,w9_3,w9_4,w9_5,disability
0,0,02/04/2020 09:56,week 1,3,4,12,"No, I have not","No, they have not",Yes,No,...,,,,,,,,,,
1,1,02/04/2020 10:01,week 1,4,0,2,"No, I have not","No, they have not",No,No,...,,,,,,,,,,
2,2,02/04/2020 10:18,week 1,3,2,1,"No, I have not","No, they have not",No,No,...,,,,,,,,,,
3,3,02/04/2020 10:35,week 1,2,5,1,"No, I have not","No, they have not",No,No,...,,,,,,,,,,
4,4,02/04/2020 10:41,week 1,2,0,1,"No, I have not","No, they have not",No,No,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15980,15980,25/09/2020 11:05,week 16,0,4,2,"No, I have not","No, they have not",No,No,...,No,No,No,3,Less than half of the time,More than half of the time,More than half of the time,Less than half of the time,More than half of the time,我没有因此受到限制
15981,15981,25/09/2020 11:07,week 16,3,2,2,"No, I have not","Yes, and they tested negative",No,No,...,,,,5 Agree strongly,Most of the time,More than half of the time,More than half of the time,Most of the time,More than half of the time,我没有因此受到限制
15982,15982,25/09/2020 11:13,week 16,9,9,9,"No, I have not","No, they have not",No,No,...,,,,5 Agree strongly,All the time,All the time,All the time,All the time,All the time,"有的,限制很多"
15983,15983,25/09/2020 11:18,week 16,3,7,3,"Yes, and I tested negative","Yes, and they tested negative",Yes,No,...,,,,Don't know,Most of the time,Most of the time,Most of the time,Most of the time,Most of the time,我没有因此受到限制
15984,15984,25/09/2020 11:39,week 16,2,2,0,"No, I have not","No, they have not",No,No,...,,,,2,Most of the time,Most of the time,More than half of the time,Most of the time,Most of the time,Prefer not to say / skipped

In [45]:
# Extracting the numeric part from the 'qweek' column and convert it to an integer
df['qweek'] = df['qweek'].str.extract(r'(\d+)$').astype(int)

In [46]:
df['qweek']

0         1
1         1
2         1
3         1
4         1
         ..
15980    16
15981    16
15982    16
15983    16
15984    16
Name: qweek, Length: 15985, dtype: int32

In [47]:
# List of columns to process
# List of columns to process
columns_to_process = [
    "i1_health", "i2_health", "i7a_health", "i3_health", "i4_health",
    "i5_health_1", "i5_health_2", "i5_health_3", "i5_health_4", "i5_health_5",
    "i5_health_99", "i5a_health", "i6_health", "i7b_health", "i8_health", "i9_health",
    "i10_health", "i11_health", "i12_health_1", "i12_health_2", "i12_health_3",
    "i12_health_4", "i12_health_5", "i12_health_6", "i12_health_7", "i12_health_8",
    "i12_health_9", "i12_health_10", "i12_health_11", "i12_health_12", "i12_health_13",
    "i12_health_14", "i12_health_15", "i12_health_16", "i12_health_17", "i12_health_18",
    "i12_health_19", "i12_health_20", "i13_health", "i14_health_1", "i14_health_2",
    "i14_health_3", "i14_health_4", "i14_health_5", "i14_health_6", "i14_health_7",
    "i14_health_8", "i14_health_9", "i14_health_10", "i14_health_96", "i14_health_98",
    "i14_health_99", "i14_health_other", "d1_health_1", "d1_health_2", "d1_health_3",
    "d1_health_4", "d1_health_5", "d1_health_6", "d1_health_7", "d1_health_8",
    "d1_health_9", "d1_health_10", "d1_health_11", "d1_health_12", "d1_health_13",
    "d1_health_98", "d1_health_99", "household_children", "weight", "gender", "age",
    "city", "household_size", "employment_status_1", "employment_status_2", 
    "employment_status_3", "employment_status_4", "employment_status_5", 
    "employment_status_6", "employment_status_7", "cantril_ladder", "WCRV_4", 
    "CORE_B2_4", "PHQ4_1", "PHQ4_2", "PHQ4_3", "PHQ4_4", "m1_1", "m1_2", "m1_3", 
    "m1_4", "m2", "m3", "m4_1", "m4_2", "m4_3", "m4_4", "m4_96", "m4_99", 
    "m4_other", "m5_1", "m5_2", "m6_1", "m6_2", "m6_3", "m6_4", "m6_5", "m6_6", 
    "m6_7", "m6_8", "m6_96", "m6_other", "m7_1", "m7_2", "m7_3", "m7_4", "m7_5", 
    "m7_6", "m7_8", "m7_9", "m7_10", "m7_11", "m8_1", "m8_2", "m8_3", "m8_4", 
    "m8_5", "m8_6", "m8_7", "m8_8", "m8_96", "m8_99", "m8_other", "m9_1", "m9_2", 
    "m9_3", "m9_4", "m9_5", "m9_6", "m9_7", "m10", "m11", "m12_1", "m12_2", 
    "m12_3", "m12_4", "m12_5", "m12_6", "m12_7", "m12_8", "m12_96", "m12_99", 
    "m12_other", "m13_1", "m13_2", "m13_3", "m13_4", "m13_5", "m13_6", "m13_8", 
    "m13_9", "m13_10", "m13_11", "v1", "v2_1", "v2_2", "v2_3", "v2_4", "v2_5", 
    "v2_99", "v3", "v3_open", "v4_1", "v4_2", "v4_3", "v4_4", "v4_5", "v4_96", 
    "v4_99", "v3_other", "i12_health_21", "i12_health_22", "i12_health_23", 
    "i12_health_24", "i12_health_25", "r1_1", "r1_2", "r1_3", "r1_4", "r1_5", 
    "r1_6", "r1_7", "m14_1", "m14_2", "m14_3", "m14_4", "m14_5", "m14_6", 
    "m14_7", "m14_8", "m14_9", "m14_10", "m14_11", "m14_96", "m14_99", 
    "m14_open", "i14_health_11", "i12_health_26", "ox1_1", "ox1_2", "ox5_1", 
    "ox4_1_1", "ox4_2_1", "ox4_3_1", "ox4_4_1", "ox4_5_1", "ox4_6_1", "ox4_7_1", 
    "ox4_8_1", "ox4_9_1", "ox4_10_1", "ox4_11_1", "w4_1", "w4_2", "w4_3", 
    "w4_4", "w4_5", "w4_6", "w4_7", "w4_8", "w4_9", "w4_10", "w4_11", "w4_99", 
    "w4_98", "w4b", "w5_1", "w5_2", "w5_3", "w5_4", "w5_5", "w5_6", "w5_7", 
    "w5_8", "w5_9", "w5_10", "w5_11", "w5_12", "w5_13", "w5_14", "w5_15", 
    "w5_16", "w5_96", "w5_99", "w5_98", "w7", "w9_1", "w9_2", "w9_3", "w9_4", 
    "w9_5", "disability"
]

for column in columns_to_process:
    df[column] = df[column].apply(
        lambda x: x if pd.api.types.is_numeric_dtype(type(x)) or pd.isna(x)
        else str(x).strip('"').strip().split()[0] if str(x).strip() else ""
    )

In [48]:
df

,RecordNo,endtime,qweek,i1_health,i2_health,i7a_health,i3_health,i4_health,i5_health_1,i5_health_2,...,w5_96,w5_99,w5_98,w7,w9_1,w9_2,w9_3,w9_4,w9_5,disability
0,0,02/04/2020 09:56,1,3,4,12,"No,","No,",Yes,No,...,,,,,,,,,,
1,1,02/04/2020 10:01,1,4,0,2,"No,","No,",No,No,...,,,,,,,,,,
2,2,02/04/2020 10:18,1,3,2,1,"No,","No,",No,No,...,,,,,,,,,,
3,3,02/04/2020 10:35,1,2,5,1,"No,","No,",No,No,...,,,,,,,,,,
4,4,02/04/2020 10:41,1,2,0,1,"No,","No,",No,No,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15980,15980,25/09/2020 11:05,16,0,4,2,"No,","No,",No,No,...,No,No,No,3,Less,More,More,Less,More,我没有因此受到限制
15981,15981,25/09/2020 11:07,16,3,2,2,"No,","Yes,",No,No,...,,,,5,Most,More,More,Most,More,我没有因此受到限制
15982,15982,25/09/2020 11:13,16,9,9,9,"No,","No,",No,No,...,,,,5,All,All,All,All,All,"有的,限制很多"
15983,15983,25/09/2020 11:18,16,3,7,3,"Yes,","Yes,",Yes,No,...,,,,Don't,Most,Most,Most,Most,Most,我没有因此受到限制
15984,15984,25/09/2020 11:39,16,2,2,0,"No,","No,",No,No,...,,,,2,Most,Most,More,Most,Most,Prefer

In [49]:
import pandas as pd
df = df.drop(columns=["disability"])

categorical_columns = [column for column in df.columns if df[column].dtype == 'object' and not df[column].str.isnumeric().all()]
df_encoded = pd.get_dummies(df, columns=categorical_columns, drop_first=False)

print(df_encoded.head())

   RecordNo  qweek  i1_health  i2_health  i7a_health  i13_health    weight  \
0         0      1          3          4          12           4  0.976602
1         1      1          4          0           2          12  1.089324
2         2      1          3          2           1           2  1.055401
3         3      1          2          5           1           5  0.997021
4         4      1          2          0           1           3  1.175887

   age  endtime_01/05/2020 00:03  endtime_01/05/2020 00:04  ...  w9_4_More  \
0   35                     False                     False  ...      False
1   53                     False                     False  ...      False
2   21                     False                     False  ...      False
3   39                     False                     False  ...      False
4   57                     False                     False  ...      False

   w9_4_Most  w9_4_Some  w9_5_  w9_5_All  w9_5_At  w9_5_Less  w9_5_More  \
0      False      False   True     False    False      False      False
1      False      False   True     False    False      False      False
2      False      False   True     False    False      False      False
3      False      False   True     False    False      False      False
4      False      False   True     False    False      False      False

   w9_5_Most  w9_5_Some
0      False      False
1      False      False
2      False      False
3      False      False
4      False      False

[5 rows x 13115 columns]

In [51]:
# Remove columns that are completely empty (all NaN values)
df_cleaned = df_encoded.dropna(axis=1, how='all')

# If you want to drop columns that have a high percentage of missing values, you can set a threshold
# Example: Drop columns with more than 30% missing values
threshold = 0.3
df_cleaned = df_encoded[df_encoded.columns[df_encoded.isnull().mean() < threshold]]

In [52]:
df_cleaned

,RecordNo,qweek,i1_health,i2_health,i7a_health,i13_health,weight,age,endtime_01/05/2020 00:03,endtime_01/05/2020 00:04,...,w9_4_More,w9_4_Most,w9_4_Some,w9_5_,w9_5_All,w9_5_At,w9_5_Less,w9_5_More,w9_5_Most,w9_5_Some
0,0,1,3,4,12,4,0.976602,35,False,False,...,False,False,False,True,False,False,False,False,False,False
1,1,1,4,0,2,12,1.089324,53,False,False,...,False,False,False,True,False,False,False,False,False,False
2,2,1,3,2,1,2,1.055401,21,False,False,...,False,False,False,True,False,False,False,False,False,False
3,3,1,2,5,1,5,0.997021,39,False,False,...,False,False,False,True,False,False,False,False,False,False
4,4,1,2,0,1,3,1.175887,57,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15980,15980,16,0,4,2,3,0.877564,22,False,False,...,False,False,False,False,False,False,False,True,False,False
15981,15981,16,3,2,2,3,1.036518,30,False,False,...,False,True,False,False,False,False,False,True,False,False
15982,15982,16,9,9,9,3,1.036518,25,False,False,...,False,False,False,False,True,False,False,False,False,False
15983,15983,16,3,7,3,2,0.782484,31,False,False,...,False,True,False,False,False,False,False,False,True,False
15984,15984,16,2,2,0,3,1.036518,29,False,False,...,False,True,False,False,False,False,False,False,True,False